Bump app version
JID-2111/JID-2111 pull request #132
Opened 2022-10-06 04:39 UTC by adityavidyadharan

# Description

Include a summary of the changes and the related issue.

## Link to the issue you are closing

Fixes # (issue)

## Screenshot or other testing that you have completed

Your PR should include at least one test/screenshot in order to showcase that the changes don't break/fix what was needed. In the case of frontend, a screenshot should suffice. For backend, depending on the scenario, some temporary tests may need to be written to show that the function does what's needed.

# Checklist:

- [ ] ESLint passes
- [ ] Prettier passes
- [ ] Included comments where necessary
- [ ] Updated README if needed
- [ ] Verified that code runs and generates no errors/warnings

2022-10-09 17:32 UTC, alex-hobby requested changes

2022-10-09 17:32 UTC, alex-hobby commented on package-lock.json
> +      "license": "Apache-2.0",
Good catch

2022-10-09 17:32 UTC, alex-hobby commented on src/renderer/components/Recent.tsx
> +            `asdf` +
Maybe we can replace the password with four asterisks? That's how MongoDB Compass does it actually
```suggestion
            `****` +
```

2022-10-09 19:22 UTC, insaan21 approved these changes
nice!, can you wait to merge until my pr gets merged into your branch

2022-10-10 05:31 UTC, alex-hobby approved these changes

2022-10-10 13:43 UTC, merged