Unit test entites
JID-2111/JID-2111 pull request #144
Opened 2022-10-11 01:09 UTC by adityavidyadharan

# Description

Defined the basic structure for the entities needed to save unit tests to memory

## Link to the issue you are closing

Fixes #127 

## Screenshot or other testing that you have completed

<img width="545" alt="Screen Shot 2022-10-10 at 9 08 51 PM" src="https://user-images.githubusercontent.com/25249258/194975305-b8dbd6b9-a982-4ab0-a9d2-777f2530ee64.png">

# Checklist:

- [ ] ESLint passes
- [ ] Prettier passes
- [ ] Included comments where necessary
- [ ] Updated README if needed
- [ ] Verified that code runs and generates no errors/warnings

2022-10-11 01:23 UTC, adityavidyadharan commented
Pending team discussion before merging

2022-10-12 02:53 UTC, insaan21 commented on src/db/entity/UnitTestEntity.ts
> +export class UnitTestEntity {
```suggestion
class UnitTestEntity {
```

2022-10-12 03:02 UTC, insaan21 commented on src/db/entity/ExecutionEntity.ts
> +  rules: RuleEntity[];
I think you'll need an on delete cascade here to delete all the rule groups once an execution is deleted?

2022-10-12 03:15 UTC, insaan21 submitted a review, later dismissed
This looks good apart from the small things I mentioned. Actually super neat!

2022-10-12 03:15 UTC, insaan21 commented on src/db/entity/ExecutionEntity.ts
> +      onDelete: 'CASCADE',
You also might want to add on update cascades everywhere: https://www.sqlite.org/foreignkeys.html#:~:text=The%20ON%20DELETE%20and%20ON,defaults%20to%20%22NO%20ACTION%22.
There should be some way to just easily configure this globally

2022-10-12 03:16 UTC, insaan21 commented on src/db/entity/ExecutionEntity.ts
> +      onDelete: 'CASCADE',
Never mind there isn't, might just have to on update cascades everywhere

2022-10-12 03:37 UTC, adityavidyadharan commented on src/db/entity/UnitTestEntity.ts
> +export class UnitTestEntity {
Class is used in `RuleEntity`

2022-10-12 18:14 UTC, insaan21 requested changes, later dismissed
Make Connection to Execution Many to One

2022-10-14 18:31 UTC, insaan21 approved these changes

2022-10-14 20:02 UTC, merged